version: "3"
services:
  boilerplate-api:
    image: sekka-booking
    environment:
      - MONGO_URI=mongodb+srv://ali:ali@cluster0.n0odb9k.mongodb.net/test 
    volumes:
      - .:/app
    ports:
      - "3030:3030"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
      


